FROM nginx:1.19-alpine

RUN rm /etc/nginx/conf.d/default.conf; mkdir -p /usr/src/app/public; rm -fr /usr/share/nginx/html
RUN ln -s /usr/src/app/public /usr/share/nginx/html
COPY nclouds/nginx.conf /etc/nginx/conf.d/default.conf
